#!/usr/bin/env bash
# Generates clearly-marked LOCAL-ONLY dev secrets for the Compose baseline.
# Production values come exclusively from OCI Vault (ADR-056).
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/secrets/local"
mkdir -p "$DIR"

gen_hex() { openssl rand -hex 32; }

for name in postgres_password session_signing_key resend_api_key gemini_api_key; do
  gen_hex > "$DIR/$name.txt"
done

cat > "$DIR/LOCAL_ONLY_MARKER.txt" <<'EOF'
LOCAL DEVELOPMENT SECRETS ONLY.
Generated by scripts/dev-secrets.sh. Git-ignored; never commit.
Production secrets come exclusively from OCI Vault (ADR-056).
EOF

chmod 600 "$DIR"/*.txt
echo "Local-only dev secrets written to $DIR"
