# Generates clearly-marked LOCAL-ONLY dev secrets for the Compose baseline.
# Production values come exclusively from OCI Vault (ADR-056).

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$dir = Join-Path $root "secrets\local"
New-Item -ItemType Directory -Force -Path $dir | Out-Null

function New-HexSecret {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $bytes = New-Object byte[] 32
    $rng.GetBytes($bytes)
    return ([BitConverter]::ToString($bytes)).Replace("-", "").ToLowerInvariant()
  } finally {
    $rng.Dispose()
  }
}

foreach ($name in @("postgres_password", "session_signing_key", "resend_api_key", "gemini_api_key")) {
  Set-Content -LiteralPath (Join-Path $dir "$name.txt") -Value (New-HexSecret) -NoNewline -Encoding ascii
}

@"
LOCAL DEVELOPMENT SECRETS ONLY.
Generated by scripts/dev-secrets.ps1. Git-ignored; never commit.
Production secrets come exclusively from OCI Vault (ADR-056).
"@ | Set-Content -LiteralPath (Join-Path $dir "LOCAL_ONLY_MARKER.txt") -Encoding ascii

Write-Output "Local-only dev secrets written to $dir"
